name: Cypress Testing Workshop pipeline

on: workflow_dispatch

jobs:
    testing:
        runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> 13b4842 (pipeline workshop - commit my chnages)
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

<<<<<<< HEAD
            - name: Run Cypress testing
=======
            - name: Run Cypress tests
>>>>>>> 13b4842 (pipeline workshop - commit my chnages)
              run: npm run e2e:full

            - name: Upload the testing results
              uses: actions/upload-pages-artifact@v3
              with:
<<<<<<< HEAD
                path: build/cypress

=======
                  name: build/cypress
>>>>>>> 13b4842 (pipeline workshop - commit my chnages)
