name: Cypress Testing Workshop pipeline

on: 
    workflow_dispatch:
    push:
    pull_request:

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Run Cypress testing
              run: npm run e2e:full

            - name: Upload the testing results
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/cypress